cas:
  #Required properties
  server-url-prefix: https://localhost:8443/cas
  server-login-url: https://localhost:8443/cas/login

  
  client-host-url: https://localhost:8444/

  #Optional properties
  authentication-url-patterns: [/protected, /protected2, /json]
  validation-url-patterns: [/protected, /protected2, /json]
  request-wrapper-url-patterns: [/protected, /protected2, /json]
  assertion-thread-local-url-patterns: [/*]
  single-logout:
    enabled: true

  #One of CAS3, CAS, or SAML. The default is CAS3 if not explicitly specified
  #validation-type: SAML

  #gateway: true
  use-session: true
  #redirect-after-validation: false
  #allowed-proxy-chains: ['https://localhost:8443/proxy1', 'https://localhost:8443/proxy2']
  #proxy-callback-url: https://localhost:8443/proxy-callback
  #proxy-receptor-url: /proxy-callback
  #accept-any-proxy: true

casLogoutUrl: https://localhost:8443/cas/logout?service=https://localhost:8444/

spring:
  thymeleaf:
    # For dev-time hot reloading of templates. Should be disabled in production
    cache: false

#Sample embedded servlet container SSL config and session tracking mode. Change as appropriate for your local deployment environment
server:
  port: 8444
  session:
    cookie:
      http-only: true
    tracking-modes: COOKIE
  ssl:
    enabled: true
    key-store: /etc/cas/thekeystore
    key-store-password: changeit
  #For 'renew' param, latest Java CAS client requires that it is set as the Servlet 'context-param'. This is how to easily set it in Spring Boot
  #context-parameters.renew: true

logging.level:
    org.jasig.cas: DEBUG
